FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_APP=backend/flask_app/app.py
EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "backend.flask_app.app:app"]
